#  docker-compose
version: "3.8"

services:
  db_docker_host_sql_and_api:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=sql_and_api_db
#      -
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      -
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 3
  app:
    depends_on:
      - db_docker_host_sql_and_api
    restart: on-failure
    image: sql-and-api:v01
    build: .
    env_file: ./.env
    ports:
      - "8080:8080"
      - "5005:5005"

    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://db_docker_host_sql_and_api:3306/sql_and_api_db?serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "validate"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
